### ISSUE TITLE
Deny access error

### ISSUE THREAD

**Issue by kn4rfy** [jaredhanson/passport-goodreads#2]
If I deny access when authenticating with goodreads, It thows error with callback:
`/api/auth/callback/goodreads?oauth_token=6C0dS5JT63I3JoKE4nv2Sg&authorize=0`

```
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuthStrategy._createOAuthError (/Users/kn4rfy/Git/matchboox-web/node_modules/passport-oauth1/lib/strategy.js:396:17)
    at /Users/kn4rfy/Git/matchboox-web/node_modules/passport-oauth1/lib/strategy.js:154:43
    at /Users/kn4rfy/Git/matchboox-web/node_modules/oauth/lib/oauth.js:465:22
    at passBackControl (/Users/kn4rfy/Git/matchboox-web/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/Users/kn4rfy/Git/matchboox-web/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by bscott** [comment]
I'm getting same error
